# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build hedera-api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t hedera-api`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system hedera-api && \
          adduser --system -G hedera-api hedera-api

COPY dist/hedera-api hedera-api/
RUN chown -R hedera-api:hedera-api .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix hedera-api --omit=dev -f install

CMD [ "node", "hedera-api" ]
